# Generated by Django 4.2.1 on 2024-01-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site', models.CharField(max_length=20)),
                ('pair', models.CharField(max_length=20)),
                ('pair1', models.CharField(max_length=20, null=True)),
                ('pair2', models.CharField(max_length=20, null=True)),
                ('askPrice', models.FloatField()),
                ('askSize', models.FloatField()),
                ('priсe', models.FloatField()),
                ('bidSize', models.FloatField()),
                ('bid', models.FloatField()),
                ('priсe_1m', models.FloatField(null=True)),
                ('datetime_1m', models.DateTimeField(null=True)),
                ('priсe_5m', models.FloatField(null=True)),
                ('datetime_5m', models.DateTimeField(null=True)),
                ('priсe_15m', models.FloatField(null=True)),
                ('datetime_15m', models.DateTimeField(null=True)),
                ('priсe_30m', models.FloatField(null=True)),
                ('datetime_30m', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20, null=True)),
                ('binance', models.FloatField(max_length=20, null=True)),
                ('huobi', models.FloatField(max_length=20, null=True)),
                ('gateio', models.FloatField(max_length=20, null=True)),
                ('kucoin', models.FloatField(max_length=20, null=True)),
                ('rubs', models.FloatField(max_length=20, null=True)),
                ('dolars', models.FloatField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='settingAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(max_length=20, null=True)),
            ],
        ),
    ]
