# Generated by Django 4.2.1 on 2024-01-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingall',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
