# Generated by Django 4.2.1 on 2024-01-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0002_settingall_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitprice',
            name='buy',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profitprice',
            name='profit',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profitprice',
            name='sell',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
