# Generated by Django 4.2.1 on 2024-01-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0003_profitprice_buy_profitprice_profit_profitprice_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitprice',
            name='buy',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profitprice',
            name='sell',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
