# Generated by Django 4.2.1 on 2024-01-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0004_alter_profitprice_buy_alter_profitprice_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitprice',
            name='round',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
