# Generated by Django 4.2.1 on 2024-01-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0005_profitprice_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitprice',
            name='spred',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
