# Generated by Django 4.2.1 on 2024-01-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0006_profitprice_spred'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitprice',
            name='buyurl',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profitprice',
            name='sellurl',
            field=models.URLField(null=True, unique=True),
        ),
    ]
