# Generated by Django 4.2.1 on 2024-01-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0007_profitprice_buyurl_profitprice_sellurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitprice',
            name='pair1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profitprice',
            name='pair2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
