# Generated by Django 4.2.1 on 2024-01-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0008_profitprice_pair1_profitprice_pair2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitPrice2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=20, null=True)),
                ('paur2', models.CharField(max_length=20, null=True)),
                ('paur3', models.CharField(max_length=20, null=True)),
                ('paurstart', models.CharField(max_length=20, null=True)),
                ('balance', models.FloatField(max_length=20, null=True)),
                ('dohod', models.FloatField(max_length=20, null=True)),
            ],
        ),
    ]
