# Generated by Django 4.2.1 on 2024-01-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0011_profitprice2_paurstart2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitprice2',
            name='paur2url',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='paur3url',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='paurstart2url',
            field=models.URLField(null=True, unique=True),
        ),
    ]
