# Generated by Django 4.2.1 on 2024-01-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0012_profitprice2_paur2url_profitprice2_paur3url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitprice2',
            name='paurstart2url',
            field=models.URLField(null=True),
        ),
    ]
