# Generated by Django 4.2.1 on 2024-01-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0013_alter_profitprice2_paurstart2url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitprice2',
            name='buy1',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='buy2',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='buyask1',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='buyask2',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='dohodsyda',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='dohodtyda',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='sell1',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='sell2',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='sellask1',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='sellask2',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
