# Generated by Django 4.2.1 on 2024-01-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0014_profitprice2_buy1_profitprice2_buy2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitprice2',
            name='buy3',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='buyask3',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='sell3',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='sellask3',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
