# Generated by Django 4.2.1 on 2024-01-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0015_profitprice2_buy3_profitprice2_buyask3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberdata',
            name='datetime_12h',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='numberdata',
            name='datetime_1d',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='numberdata',
            name='datetime_1h',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='numberdata',
            name='datetime_3h',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='numberdata',
            name='datetime_6h',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='numberdata',
            name='priсe_12h',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='numberdata',
            name='priсe_1d',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='numberdata',
            name='priсe_1h',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='numberdata',
            name='priсe_3h',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='numberdata',
            name='priсe_6h',
            field=models.FloatField(null=True),
        ),
    ]
