# Generated by Django 4.2.1 on 2024-02-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0016_numberdata_datetime_12h_numberdata_datetime_1d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitprice2',
            name='dvizhenie_valut_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='dvizhenie_valut_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='dvizhenie_valut_4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='idpaur2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='idpaur3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='idpaur4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='speed_valute_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='speed_valute_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profitprice2',
            name='speed_valute_4',
            field=models.IntegerField(null=True),
        ),
    ]
