# Generated by Django 4.2.1 on 2024-02-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0017_profitprice2_dvizhenie_valut_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitprice2',
            name='datetime_uploder',
            field=models.DateTimeField(null=True),
        ),
    ]
