# Generated by Django 4.2.1 on 2024-02-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0018_profitprice2_datetime_uploder'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashbord_torgov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
            ],
        ),
    ]
