# Generated by Django 4.2.1 on 2024-02-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0019_dashbord_torgov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashbord_torgov',
            name='site',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
