# Generated by Django 4.2.1 on 2024-02-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0020_alter_dashbord_torgov_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashbord_torgov',
            name='balance1',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='balance2',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
