# Generated by Django 4.2.1 on 2024-02-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0023_dashbord_torgov_data_torgov_dashbord_torgov_dohod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashbord_torgov',
            name='balance1',
        ),
        migrations.RemoveField(
            model_name='dashbord_torgov',
            name='balance2',
        ),
    ]
