# Generated by Django 4.2.1 on 2024-02-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0024_remove_dashbord_torgov_balance1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_askPrice',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_askSize',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_bid',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_bidSize',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_datetime_12h',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_datetime_15m',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_datetime_1d',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_datetime_1h',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_datetime_1m',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_datetime_30m',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_datetime_3h',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_datetime_5m',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_datetime_6h',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_pair',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_pair1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_pair2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_priсe',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_priсe_12h',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_priсe_15m',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_priсe_1d',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_priсe_1h',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_priсe_1m',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_priсe_30m',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_priсe_3h',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_priсe_5m',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dashbord_torgov',
            name='theer_priсe_6h',
            field=models.FloatField(null=True),
        ),
    ]
