# Generated by Django 4.2.1 on 2024-02-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0026_alter_dashbord_torgov_data_torgov_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashbord_torgov',
            name='dvizhenie_start',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dashbord_torgov',
            name='price_start',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dashbord_torgov',
            name='speed_start',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
