# Generated by Django 4.2.1 on 2024-02-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0027_alter_dashbord_torgov_dvizhenie_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashbord_torgov',
            name='dvizhenie_end',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dashbord_torgov',
            name='dvizhenie_pair1',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dashbord_torgov',
            name='dvizhenie_pair2',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dashbord_torgov',
            name='price_end',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dashbord_torgov',
            name='price_pair1',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dashbord_torgov',
            name='price_pair2',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dashbord_torgov',
            name='speed_end',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dashbord_torgov',
            name='speed_pair1',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dashbord_torgov',
            name='speed_pair2',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
