# Generated by Django 4.2.1 on 2024-02-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0028_alter_dashbord_torgov_dvizhenie_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashbord_torgov',
            name='dvizhenie_start',
        ),
        migrations.RemoveField(
            model_name='dashbord_torgov',
            name='speed_start',
        ),
    ]
