# Generated by Django 4.2.1 on 2024-04-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0029_remove_dashbord_torgov_dvizhenie_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('pair_step_1', models.CharField(max_length=100)),
                ('pair_step_1_pair1', models.CharField(max_length=100)),
                ('pair_step_1_pair2', models.CharField(max_length=100)),
                ('pair_step_1_price', models.CharField(max_length=100)),
                ('pair_step_2', models.CharField(max_length=100)),
                ('pair_step_2_pair1', models.CharField(max_length=100)),
                ('pair_step_2_pair2', models.CharField(max_length=100)),
                ('pair_step_2_price', models.CharField(max_length=100)),
                ('pair_step_3', models.CharField(max_length=100)),
                ('pair_step_3_pair1', models.CharField(max_length=100)),
                ('pair_step_3_pair2', models.CharField(max_length=100)),
                ('pair_step_3_price', models.CharField(max_length=100)),
                ('dohod_go', models.CharField(max_length=100)),
                ('dohod_back', models.CharField(max_length=100)),
            ],
        ),
    ]
