# Generated by Django 4.2.1 on 2024-04-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0030_tradepair'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradepair',
            name='up_Data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
