# Generated by Django 4.2.1 on 2024-05-01 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0031_tradepair_up_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradepair',
            name='pair_step_1_price_line_down',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradepair',
            name='pair_step_1_price_line_up',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradepair',
            name='pair_step_2_price_line_down',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradepair',
            name='pair_step_2_price_line_up',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradepair',
            name='pair_step_3_price_line_down',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradepair',
            name='pair_step_3_price_line_up',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
