# Generated by Django 4.2.1 on 2024-05-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0032_tradepair_pair_step_1_price_line_down_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('pair_step_1_pair2', models.CharField(max_length=100)),
                ('pair_step_1_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pair_step_2_pair2', models.CharField(max_length=100)),
                ('pair_step_2_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pair_step_3_pair2', models.CharField(max_length=100)),
                ('pair_step_3_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fakt_dohod', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
