# Generated by Django 4.2.1 on 2024-05-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0033_tradingpair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpair',
            name='fakt_dohod',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='pair_step_1_pair2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='pair_step_1_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='pair_step_2_pair2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='pair_step_2_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='pair_step_3_pair2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='pair_step_3_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
