# Generated by Django 4.2.1 on 2024-05-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0034_alter_tradingpair_fakt_dohod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpair',
            name='fakt_dohod',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='pair_step_1_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='pair_step_2_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='pair_step_3_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
