# Generated by Django 4.2.1 on 2024-05-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0035_alter_tradingpair_fakt_dohod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpair',
            name='fakt_dohod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='pair_step_1_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='pair_step_2_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='pair_step_3_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
