# Generated by Django 4.2.1 on 2024-05-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0036_alter_tradingpair_fakt_dohod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpair',
            name='lisen_pair',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
