# Generated by Django 4.2.1 on 2024-05-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0038_tradingpair_way_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpair',
            name='price_pair',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
