# Generated by Django 4.2.1 on 2024-05-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0041_tradepairrsi_up_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpairrsi',
            name='user_rsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
