# Generated by Django 4.2.1 on 2024-05-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0042_tradingpairrsi_user_rsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpair',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
