# Generated by Django 4.2.1 on 2024-05-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0043_tradingpair_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingpairrsi',
            old_name='lisen_pair_rsi',
            new_name='lisen_pair',
        ),
        migrations.RenameField(
            model_name='tradingpairrsi',
            old_name='price_pair_rsi',
            new_name='price_pair',
        ),
        migrations.RenameField(
            model_name='tradingpairrsi',
            old_name='user_rsi',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tradingpairrsi',
            old_name='way_pair_rsi',
            new_name='way_pair',
        ),
    ]
