# Generated by Django 4.2.1 on 2024-05-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0044_rename_lisen_pair_rsi_tradingpairrsi_lisen_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradepairrsi',
            name='off_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
