# Generated by Django 4.2.1 on 2024-05-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0046_alter_tradepairrsi_off_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradepairrsi',
            name='off_on',
            field=models.BooleanField(default=True, verbose_name='Переключатель'),
        ),
    ]
