# Generated by Django 4.2.1 on 2024-06-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0047_alter_tradepairrsi_off_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradepairrsi',
            name='norm',
            field=models.BooleanField(default=True, verbose_name='Переключатель'),
        ),
    ]
