# Generated by Django 4.2.1 on 2024-06-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0048_tradepairrsi_norm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utm_metci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('utm', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tradepairrsi',
            name='norm',
            field=models.BooleanField(default=True, verbose_name='Переключатель2'),
        ),
    ]
