# Generated by Django 4.2.1 on 2024-06-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0049_utm_metci_alter_tradepairrsi_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='utm_metci',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
